# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'aims.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from utils.api.google.gsheets import Gsheet
from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import QLineEdit, QPushButton, QWidget
from handler import CastAlbumUtil, UtilMediator, SearchUtil
from utils.Album import Album



class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1055, 829)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.stackedWidget = QtWidgets.QStackedWidget(self.centralwidget)
        self.stackedWidget.setGeometry(QtCore.QRect(70, 50, 911, 661))
        self.stackedWidget.setObjectName("stackedWidget")
        self.search_page = QtWidgets.QWidget()
        self.search_page.setObjectName("search_page")
        
        self.label = QtWidgets.QLabel(self.search_page)
        self.label.setGeometry(QtCore.QRect(20, 20, 271, 121))
        font = QtGui.QFont()
        font.setPointSize(21)
        font.setBold(True)
        font.setUnderline(False)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.search_page)
        self.label_2.setGeometry(QtCore.QRect(110, 260, 81, 20))
        self.label_2.setObjectName("label_2")
        
        self.search_pushButton = QtWidgets.QPushButton(self.search_page)
        self.search_pushButton.setGeometry(QtCore.QRect(110, 330, 151, 31))
        self.search_pushButton.setObjectName("search_pushButton")
        self.search_pushButton.clicked.connect(self.search_button_click)    ##connecting to search command
       
        
        self.artist_lineEdit = QtWidgets.QLineEdit(self.search_page)
        self.artist_lineEdit.setGeometry(QtCore.QRect(190, 260, 186, 20))
        self.artist_lineEdit.setObjectName("artist_lineEdit")
    
        
        self.title_lineEdit = QtWidgets.QLineEdit(self.search_page)
        self.title_lineEdit.setGeometry(QtCore.QRect(190, 300, 186, 20))
        self.title_lineEdit.setObjectName("title_lineEdit")
        
        self.label_3 = QtWidgets.QLabel(self.search_page)
        self.label_3.setGeometry(QtCore.QRect(110, 300, 81, 20))
        self.label_3.setObjectName("label_3")
        
    
        #PAGE 2
        self.stackedWidget.addWidget(self.search_page)
        
        self.album_display_page = QtWidgets.QWidget()
        self.album_display_page.setObjectName("album_display_page")
        
        self.image_label = QtWidgets.QLabel(self.album_display_page)
        self.image_label.setGeometry(QtCore.QRect(30, 30, 300, 300))
        self.image_label.setObjectName("image_label")
        
        self.artist_name_label = QtWidgets.QLabel(self.album_display_page)
        self.artist_name_label.setGeometry(QtCore.QRect(410, 40, 191, 61))
        self.artist_name_label.setObjectName("artist_name_label")
        
        self.album_title_label = QtWidgets.QLabel(self.album_display_page)
        self.album_title_label.setGeometry(QtCore.QRect(410, 110, 191, 61))
        self.album_title_label.setObjectName("album_title_label")
        
        self.back_pushButton = QtWidgets.QPushButton(self.album_display_page)
        self.back_pushButton.setGeometry(QtCore.QRect(720, 600, 121, 51))
        self.back_pushButton.setObjectName("back_pushButton")
        self.stackedWidget.addWidget(self.album_display_page)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1055, 21))
        self.menubar.setObjectName("menubar")
        self.menuSearch = QtWidgets.QMenu(self.menubar)
        self.menuSearch.setObjectName("menuSearch")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionSearch_Album = QtWidgets.QAction(MainWindow)
        self.actionSearch_Album.setObjectName("actionSearch_Album")
        self.actionView_Inventory = QtWidgets.QAction(MainWindow)
        self.actionView_Inventory.setObjectName("actionView_Inventory")
        self.menuSearch.addAction(self.actionSearch_Album)
        self.menuSearch.addAction(self.actionView_Inventory)
        self.menubar.addAction(self.menuSearch.menuAction())
        self.label_2.setBuddy(self.artist_lineEdit)
        self.label_3.setBuddy(self.artist_lineEdit)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
    
    
    def search_button_click(self):
        handler = SearchUtil(self.artist_lineEdit, self.title_lineEdit)
        caster = CastAlbumUtil(self.image_label, self.artist_name_label, self.album_title_label, self.album_display_page, self.stackedWidget)
        mediator = UtilMediator(handler, caster)
        handler.search_album()
        caster.cast_album()
        
        
        
    

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "Album Search"))
        self.label_2.setText(_translate("MainWindow", "Artist Name"))
        self.search_pushButton.setText(_translate("MainWindow", "Search"))
        self.label_3.setText(_translate("MainWindow", "Album Title"))
        self.image_label.setText(_translate("MainWindow", "img_url"))
        self.artist_name_label.setText(_translate("MainWindow", "Artist Name"))
        self.album_title_label.setText(_translate("MainWindow", "Album Title"))
        self.back_pushButton.setText(_translate("MainWindow", "Back"))
        self.menuSearch.setTitle(_translate("MainWindow", "File"))
        self.actionSearch_Album.setText(_translate("MainWindow", "Search Album"))
        self.actionView_Inventory.setText(_translate("MainWindow", "View Inventory"))
        
class PopupWidget(QWidget):
    def __init__(self):
        super().__init__()
        
    def init_ui(self):
        button = QPushButton('CLICK', self)
        button.move(30, 30)
        button.clicked.connect()
        
    def show_cont(self):
        text , ok
        
        


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
